### ISSUE TITLE
Patch org-html-themes

### ISSUE THREAD

**Issue by ayys** [Anton-Latukha/haskell-notes#2]
First of all, I love this book! It has been my guide and savior!
Thank you so much for your contribution!

I saw the [issue](https://github.com/fniessen/org-html-themes/issues/91) @Anton-Latukha  opened over at org-html-themes repo regarding nested table-of-contents.

I have proposed a PR but the maintainer is too busy to work on the project right now, so I don't think the patches will be merged anytime soon. I would love for this project to use those patches.

[Link to patch](https://github.com/fniessen/org-html-themes/pull/107)

Again, thank you so much for this project!

**Comment by Anton-Latukha** [comment]
Thank you for sending the message and the patch.

I would write a proper fuller response when I would be in a good shape to compose it.

**Comment by ayys** [comment]
Don't mention it ;)

**Comment by Anton-Latukha** [comment]
Ok.

I already made a too long pause.

I broke my schedule for ~ a month, so almost never was in a great mood to thank you properly.

Thank you for your contribution, and help.

Indeed this patch is what I looked for a couple of times.

---

I received some responsibility to attend, was quite busy with some strategic movement.

Soon some results from there would also be included in the book. Material how to configure almost any CI for Haskell protect, simply and effectively.

---

Thank you again, and as always, as you've shown - be smart to learn from others and be generous - only that would save and cherish the life on the planet.

**Comment by Anton-Latukha** [comment]
BTW, very useful, you can share or fetch patches on GitHub by adding `.patch` to the end of PR URL:

https://github.com/fniessen/org-html-themes/pull/107.patch

---

Feels like we are sharing patches on the mailing list.

**Comment by Anton-Latukha** [comment]
Notifying you that the patch so far does not work for me using `master` everywhere.

I used current `master` of `org-html-themes`, patched it with your patch from PR.

Result - nothing changed, as you can see it here: https://blog.latukha.com/haskell-notes

`Org-mode` currently has:

```
#+OPTIONS: H:10
#+OPTIONS: num:t
#+OPTIONS: toc:10
```
And `org-export-headline-levels = 10`.

It is really that many levels required to cover the TOC of for this book, see `MonadIO type class` there for example.

Maybe your PR somehow depends on your parallel PRs, or something changed in `master` there and it still patches fine, or may be patch does not account for something.

**Comment by Anton-Latukha** [comment]
When the patch would work/merge in, you/we may notify Spacemacs.

I was helping migrating layers list there a couple or so years ago, and know that the layers there does not fit into those 3 layers.

They use the same setup and have the very same thing: https://develop.spacemacs.org/layers/LAYERS.html#multi-paradigm

The biggest section that has the most of the programming languages listed just not got into the 3 TOC levels.

**Comment by ayys** [comment]
The problem seems to be that, while you are patching the local version of org-html-themes, README.html seems to be using the upstream version. The best way would be for the upstream maintainer to apply the PR.

In the meantime, [my fork](https://github.com/ayys/org-html-themes/) of the project allows nesting to arbitrary depths. Here is a screenshot to show you a demo.
![Screenshot_2020-06-28 Fundamental Haskell notes](https://user-images.githubusercontent.com/48376475/85938092-91d9f700-b929-11ea-8291-13ddbeeae21d.png)

You can use my fork as a drop-in replacement to the current org-html-themes.

Also, you seemed to have mentioned someone else which is why I did not see this issue in time. @Anton-Latukha

**Comment by Anton-Latukha** [comment]
Yep. I grown less patient and less focused in last month as topics to address expanded exponentially. And I really started to love some typos.
There is just no way to live without leaning on Org-mode prioritization of tasks one at a time.
BTW, I fixed some upstream Org-mode code not so long ago, and now custom prioritization works in Org-mode, you can create and use your own one.
But that is of topic.

---

_"README.html seems to be using the upstream version"_

Oh my lord, thank you. Indeed, indeed may be.

Looked, seems I use it properly, IDK why patched submodule loads URL version. I would look into it further.

If upstream would not react to it in some weeks, would switch to your fork.

**Comment by Anton-Latukha** [comment]
@ayys

Thank you.

I switched to your fork, and export from Org to HTML using your fork.

As you said, noted that even the exported through the fork, the source anyway uses CSS styles from the remote central repo.
```
#+setupfile: ./org-html-themes/setup/theme-readtheorg.setup
```
Results into it, it seemed like it uses local repo, but in fact, loaded a remote style.

So switched onto:
```
#+setupfile: ./org-html-themes/setup/theme-readtheorg-local.setup
```

That is what was the cause of all this.

Also needed to do other work to make my stack work with that change.

Thank you.

**Comment by Anton-Latukha** [comment]
If upstream indeed would stall, and you would convert other upstreams to your fork, please say to me, I would also go and help switch Spacemacs and/or some other projects to it.

**Comment by Anton-Latukha** [comment]
Solved.
